version: '3.7'

services:

  rasa:
    image: rasa/rasa:1.4.5-full
    depends_on:
      - action_server
    ports:
      - 8081:5005  
    volumes:
      - .:/app
    command:
      - run
      - --cors
      - "*"
      - --enable-api
      - --debug
      - --credentials 
      - ./configs/credentials.yml
      - --endpoints
      - ./configs/endpoints.yml
    networks:
      - rasa_network

  action_server:
    image: rasa/rasa-sdk:1.4.0
    ports:
      # - 5055:5055
      - 8082:5055
    volumes:
      - ./actions:/app/actions
    networks:
      - rasa_network

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.13.1
    ports:
      - 8090:8081
    networks:
      - rasa_network


  nginx_rasa:
    image: nginx:alpine
    depends_on:
      - rasa
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./webchat:/usr/share/nginx/html
    ports:
      - 8080:8080
    networks:
      - rasa_network

networks:
  rasa_network:
