# This file contains the different endpoints your bot can use.

# Server where the models are pulled from.
# https://rasa.com/docs/rasa/user-guide/running-the-server/#fetching-models-from-a-server/

models:
 url: "http://artifactory:8081/artifactory/mychatbot-generic/model.tar.gz"
 wait_time_between_pulls:  20   # [optional](default: 100)
 basic_auth:
  username: admin
  password: password

# Server which runs your custom actions.
# https://rasa.com/docs/rasa/core/actions/#custom-actions/

action_endpoint:
  url: http://action_server:5055/webhook

# action_endpoint:
#  url: "http://localhost:5055/webhook"
# Tracker store which is used to store the conversations.
# By default the conversations are stored in memory.
# https://rasa.com/docs/rasa/api/tracker-stores/

#tracker_store:
#    type: redis
#    url: <host of the redis instance, e.g. localhost>
#    port: <port of your redis instance, usually 6379>
#    db: <number of your database within redis, e.g. 0>
#    password: <password used for authentication>

# tracker_store:
#   type:
#   url:
#   port:
#   password:
#   db:
#   record_exp:

# tracker_store:
#   type: mongod
#   url: mongodb://mongo_rasa:27017
#   username: ${MONGO_USERNAME}
#   password: ${MONGO_PASSWORD}

# Event broker which all conversation events should be streamed to.
# https://rasa.com/docs/rasa/api/event-brokers/

#event_broker:
#  url: localhost
#  username: username
#  password: password
#  queue: queue
